version: '3.7'

services:
  db:
    image: mysql:5.7   # Use MySQL image instead of MariaDB
    ports:
      - "3310:3306"     # ***
    restart: always     
    # The restart policy `always` in Docker means containers will automatically restart if they stop, unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: aaaa  # important

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5673:5672"   # is used for the AMQP protocol, allowing clients to publish and consume messages {AMQP is the protocol RabbitMQ uses for messaging}
      - "15673:15672" # used for accessing the RabbitMQ management UI for monitoring and managing the RabbitMQ server.
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8086:80"   # ***
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root   # important

  app:
    image: nextcloud
    ports:
      - "8085:80" # ***
    restart: always
    volumes:
      - nextcloud_data:/var/www/html #  ***
    environment:
      NEXTCLOUD_ADMIN_USER: admin           # ***
      NEXTCLOUD_ADMIN_PASSWORD: secret      # important
      NEXTCLOUD_TRUSTED_DOMAINS: localhost

volumes:            # file are storing in volumes, which is mounted to the /var/www/html directory inside the Nextcloud container
  nextcloud_data:
