version: '3.7'

services:
  db:
    image: mysql:5.7   # Use MySQL image instead of MariaDB
    ports:
      - "3310:3306"     # ***
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: aaaa  # important

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - "5673:5672"   # ***
      - "15673:15672" # ***
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8086:80"   # ***
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root   # important

  app:
    image: nextcloud
    ports:
      - "8085:80" # ***
    restart: always
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      NEXTCLOUD_ADMIN_USER: admin           # ***
      NEXTCLOUD_ADMIN_PASSWORD: secret      # important
      NEXTCLOUD_TRUSTED_DOMAINS: localhost

volumes:
  nextcloud_data:
